/**
 * Seed list of manufacturing-relevant 4-digit HTS headings for the public SEO
 * pages at /tariffs/[hts_code]. Each entry is a heading a small importer is
 * likely to google the day a tariff hits their invoice.
 *
 * `code` is the 4-digit heading; `chapter` is the 2-digit chapter it belongs to.
 */
export interface HtsHeading {
  code: string;
  chapter: string;
  title: string;
}

export const HTS_HEADINGS: HtsHeading[] = [
  { code: "7601", chapter: "76", title: "Unwrought aluminum" },
  { code: "7604", chapter: "76", title: "Aluminum bars, rods and profiles" },
  { code: "7606", chapter: "76", title: "Aluminum plates, sheets and strip" },
  { code: "7616", chapter: "76", title: "Other articles of aluminum" },
  { code: "7208", chapter: "72", title: "Flat-rolled iron/steel, hot-rolled" },
  { code: "7209", chapter: "72", title: "Flat-rolled iron/steel, cold-rolled" },
  { code: "7210", chapter: "72", title: "Flat-rolled iron/steel, clad/plated" },
  { code: "7304", chapter: "73", title: "Seamless iron/steel tubes and pipes" },
  { code: "7318", chapter: "73", title: "Screws, bolts, nuts and washers of iron/steel" },
  { code: "7326", chapter: "73", title: "Other articles of iron or steel" },
  { code: "8407", chapter: "84", title: "Spark-ignition internal combustion engines" },
  { code: "8409", chapter: "84", title: "Parts for internal combustion engines" },
  { code: "8413", chapter: "84", title: "Pumps for liquids" },
  { code: "8414", chapter: "84", title: "Air/vacuum pumps and compressors" },
  { code: "8421", chapter: "84", title: "Centrifuges and filtering machinery" },
  { code: "8431", chapter: "84", title: "Parts for lifting/handling machinery" },
  { code: "8471", chapter: "84", title: "Computers and data-processing units" },
  { code: "8473", chapter: "84", title: "Parts for computers and office machines" },
  { code: "8481", chapter: "84", title: "Taps, cocks, valves for pipes and tanks" },
  { code: "8482", chapter: "84", title: "Ball and roller bearings" },
  { code: "8483", chapter: "84", title: "Transmission shafts, gears and clutches" },
  { code: "8501", chapter: "85", title: "Electric motors and generators" },
  { code: "8504", chapter: "85", title: "Transformers, converters and inductors" },
  { code: "8507", chapter: "85", title: "Electric storage batteries" },
  { code: "8511", chapter: "85", title: "Ignition and starting equipment" },
  { code: "8516", chapter: "85", title: "Electric heaters and heating apparatus" },
  { code: "8517", chapter: "85", title: "Telephones and network equipment" },
  { code: "8518", chapter: "85", title: "Microphones, loudspeakers and amplifiers" },
  { code: "8536", chapter: "85", title: "Electrical switching/protecting apparatus (<1000V)" },
  { code: "8537", chapter: "85", title: "Boards, panels and control cabinets" },
  { code: "8541", chapter: "85", title: "Semiconductor devices and diodes" },
  { code: "8542", chapter: "85", title: "Electronic integrated circuits" },
  { code: "8544", chapter: "85", title: "Insulated wire and cable" },
  { code: "3901", chapter: "39", title: "Polymers of ethylene, primary forms" },
  { code: "3902", chapter: "39", title: "Polymers of propylene, primary forms" },
  { code: "3907", chapter: "39", title: "Polyacetals, polyesters and epoxides" },
  { code: "3917", chapter: "39", title: "Plastic tubes, pipes and fittings" },
  { code: "3920", chapter: "39", title: "Plastic plates, sheets and film, non-cellular" },
  { code: "3923", chapter: "39", title: "Plastic packing and closures" },
  { code: "3926", chapter: "39", title: "Other articles of plastics" },
  { code: "4011", chapter: "40", title: "New pneumatic rubber tires" },
  { code: "4016", chapter: "40", title: "Other articles of vulcanized rubber" },
  { code: "6203", chapter: "62", title: "Men's suits, jackets and trousers" },
  { code: "6204", chapter: "62", title: "Women's suits, dresses and trousers" },
  { code: "6109", chapter: "61", title: "T-shirts and vests, knitted" },
  { code: "6110", chapter: "61", title: "Sweaters and pullovers, knitted" },
  { code: "6403", chapter: "64", title: "Footwear with leather uppers" },
  { code: "6404", chapter: "64", title: "Footwear with textile uppers" },
  { code: "9401", chapter: "94", title: "Seats and chairs" },
  { code: "9403", chapter: "94", title: "Other furniture and parts" },
  { code: "9405", chapter: "94", title: "Lamps and lighting fittings" },
  { code: "4819", chapter: "48", title: "Paper and paperboard cartons and boxes" },
  { code: "4820", chapter: "48", title: "Registers, notebooks and paper stationery" },
  { code: "7013", chapter: "70", title: "Glassware for table, kitchen and household" },
  { code: "6907", chapter: "69", title: "Ceramic tiles and flags" },
  { code: "6911", chapter: "69", title: "Porcelain tableware and kitchenware" },
  { code: "8302", chapter: "83", title: "Base metal mountings and fittings" },
  { code: "8301", chapter: "83", title: "Locks and padlocks of base metal" },
  { code: "8205", chapter: "82", title: "Hand tools not elsewhere specified" },
  { code: "8207", chapter: "82", title: "Interchangeable tools for hand/machine tools" },
  { code: "9018", chapter: "90", title: "Medical, surgical and dental instruments" },
  { code: "9027", chapter: "90", title: "Instruments for physical/chemical analysis" },
  { code: "9032", chapter: "90", title: "Automatic regulating/controlling instruments" },
  { code: "8708", chapter: "87", title: "Parts and accessories for motor vehicles" },
  { code: "8714", chapter: "87", title: "Parts and accessories for bicycles" },
  { code: "8712", chapter: "87", title: "Bicycles, non-motorized" },
  { code: "9503", chapter: "95", title: "Toys, tricycles and puzzles" },
  { code: "9506", chapter: "95", title: "Sports and outdoor equipment" },
  { code: "8215", chapter: "82", title: "Spoons, forks and kitchen tableware" },
  { code: "7323", chapter: "73", title: "Iron/steel table, kitchen and household articles" },
  { code: "8467", chapter: "84", title: "Hand-held power tools" },
  { code: "8544", chapter: "85", title: "Insulated wire, cable and conductors" },
  { code: "2921", chapter: "29", title: "Amine-function organic compounds" },
  { code: "2933", chapter: "29", title: "Heterocyclic compounds with nitrogen" },
  { code: "3204", chapter: "32", title: "Synthetic organic coloring matter" },
  { code: "3208", chapter: "32", title: "Paints and varnishes, non-aqueous" },
  { code: "3402", chapter: "34", title: "Surface-active agents and detergents" },
  { code: "4202", chapter: "42", title: "Trunks, handbags and cases" },
  { code: "5407", chapter: "54", title: "Woven fabrics of synthetic filament yarn" },
  { code: "5208", chapter: "52", title: "Woven cotton fabrics (>=85% cotton)" },
  { code: "6006", chapter: "60", title: "Other knitted or crocheted fabrics" },
  { code: "8302", chapter: "83", title: "Furniture, door and window base metal fittings" },
  { code: "7907", chapter: "79", title: "Other articles of zinc" },
  { code: "7419", chapter: "74", title: "Other articles of copper" },
  { code: "7411", chapter: "74", title: "Copper tubes and pipes" },
  { code: "7408", chapter: "74", title: "Copper wire" },
  { code: "8544", chapter: "85", title: "Wiring harnesses and insulated conductors" },
  { code: "8425", chapter: "84", title: "Pulleys, winches and hoists" },
  { code: "8479", chapter: "84", title: "Machines with individual functions, n.e.s." },
  { code: "8480", chapter: "84", title: "Molds for metal, rubber and plastics" },
  { code: "9028", chapter: "90", title: "Gas, liquid and electricity supply meters" },
  { code: "9026", chapter: "90", title: "Instruments for measuring flow and pressure" },
  { code: "8443", chapter: "84", title: "Printing machinery and parts" },
  { code: "8450", chapter: "84", title: "Household or laundry washing machines" },
  { code: "8418", chapter: "84", title: "Refrigerators and freezers" },
  { code: "8415", chapter: "84", title: "Air conditioning machines" },
  { code: "9013", chapter: "90", title: "Liquid crystal devices and optical appliances" },
  { code: "8523", chapter: "85", title: "Discs, tapes and solid-state storage media" },
  { code: "8528", chapter: "85", title: "Monitors and projectors" },
];

const BY_CODE = new Map(HTS_HEADINGS.map((h) => [h.code, h]));

export function getHeading(code: string): HtsHeading | undefined {
  return BY_CODE.get(code);
}
